M48
; DRILL file {KiCad 9.0.7} date 2026-02-07T20:34:03-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-07T20:34:03-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X47.57Y-22.638
X47.57Y-26.638
T2
X16.3Y-17.018
X16.3Y-55.6
X48.768Y-17.018
X48.768Y-55.626
M30
